version: '0.2'
services:
  backend:
    build:
      context: .
      dockerfile: /backend/Dockerfile
    ports:
      - 8000:8000
    networks:
      - flexsume_network
    hostname: backend

  frontend:
    build:
      context: .
      dockerfile: /frontend/Dockerfile
    ports:
      - 80:80
    networks:
      - flexsume_network
    hostname: frontend

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=flexsume
      - POSTGRES_PASSWORD=flexsume_password
      - POSTGRES_DB=flexsume_db
    networks:
      - flexsume_network

networks:
  flexsume_network:
    driver: bridge
